import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Home/Navbar/Navbar";
import Footer from "@/components/Home/Footer/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/utils/providers/auth-provider";
import { Toaster } from "@/components/ui/sonner"; // Add this
import { Providers } from "@/utils/providers/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Niyenin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <AuthProvider>
            <Providers>
            <Header />
            {children}
            <Footer />
            </Providers>
            <Toaster /> {/* Add this */}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}